import 'package:flutter/material.dart';

enum KoogweThemeMode {
  light,
  dark,
  system,
}

enum KoogweTheme {
  defaultOrange,
  trainBooking,
  taxiBlue,
  smartHome,
  busCoral,
  fitnessGradient,
  authBrown,
  oceanBlue,
  sunsetPurple,
  forestGreen,
  midnightDark,
  cyberPunk,
}

class KoogweThemeData {
  final String name;
  final Color primary;
  final Color primaryDark;
  final Color secondary;
  final Color accent;
  final Color background;
  final Color surface;
  final Color surfaceVariant;
  final Color textPrimary;
  final Color textSecondary;
  final Color textTertiary;
  final Color border;
  final Color error;
  final Color success;
  final Color warning;
  final LinearGradient? gradientBackground;
  final String? description;
  final IconData? icon;

  const KoogweThemeData({
    required this.name,
    required this.primary,
    required this.primaryDark,
    required this.secondary,
    required this.accent,
    required this.background,
    required this.surface,
    required this.surfaceVariant,
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.border,
    required this.error,
    required this.success,
    required this.warning,
    this.gradientBackground,
    this.description,
    this.icon,
  });

  static Map<KoogweTheme, Map<KoogweThemeMode, KoogweThemeData>> get allThemes => {
    // Thème par défaut Orange KOOGWE
    KoogweTheme.defaultOrange: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Orange KOOGWE',
        description: 'Thème officiel KOOGWE',
        icon: Icons.local_taxi,
        primary: const Color(0xFFFF6B35),
        primaryDark: const Color(0xFFE85527),
        secondary: const Color(0xFF4ECDC4),
        accent: const Color(0xFFFFE66D),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFF8F9FA),
        surfaceVariant: const Color(0xFFE9ECEF),
        textPrimary: const Color(0xFF212529),
        textSecondary: const Color(0xFF6C757D),
        textTertiary: const Color(0xFFADB5BD),
        border: const Color(0xFFDEE2E6),
        error: const Color(0xFFDC3545),
        success: const Color(0xFF28A745),
        warning: const Color(0xFFFFC107),
        gradientBackground: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFFFF6B35), Color(0xFFE85527)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Orange KOOGWE',
        description: 'Thème officiel KOOGWE (Sombre)',
        icon: Icons.local_taxi,
        primary: const Color(0xFFFF6B35),
        primaryDark: const Color(0xFFE85527),
        secondary: const Color(0xFF4ECDC4),
        accent: const Color(0xFFFFE66D),
        background: const Color(0xFF121212),
        surface: const Color(0xFF1E1E1E),
        surfaceVariant: const Color(0xFF2C2C2C),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFB0B0B0),
        textTertiary: const Color(0xFF707070),
        border: const Color(0xFF3A3A3A),
        error: const Color(0xFFCF6679),
        success: const Color(0xFF4CAF50),
        warning: const Color(0xFFFFB300),
      ),
    },

    // Thème Train Booking (Orange/Blanc)
    KoogweTheme.trainBooking: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Train Booking',
        description: 'Inspiré des applications de réservation de train',
        icon: Icons.train,
        primary: const Color(0xFFFF5722),
        primaryDark: const Color(0xFFE64A19),
        secondary: const Color(0xFF2196F3),
        accent: const Color(0xFF4CAF50),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFFAFAFA),
        surfaceVariant: const Color(0xFFF5F5F5),
        textPrimary: const Color(0xFF212121),
        textSecondary: const Color(0xFF757575),
        textTertiary: const Color(0xFFBDBDBD),
        border: const Color(0xFFE0E0E0),
        error: const Color(0xFFF44336),
        success: const Color(0xFF4CAF50),
        warning: const Color(0xFFFF9800),
        gradientBackground: const LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: [Color(0xFFFF5722), Color(0xFFFF7043)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Train Booking',
        description: 'Train Booking (Sombre)',
        icon: Icons.train,
        primary: const Color(0xFFFF7043),
        primaryDark: const Color(0xFFFF5722),
        secondary: const Color(0xFF42A5F5),
        accent: const Color(0xFF66BB6A),
        background: const Color(0xFF1A1A1A),
        surface: const Color(0xFF252525),
        surfaceVariant: const Color(0xFF323232),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFB0B0B0),
        textTertiary: const Color(0xFF707070),
        border: const Color(0xFF404040),
        error: const Color(0xFFEF5350),
        success: const Color(0xFF66BB6A),
        warning: const Color(0xFFFFB74D),
      ),
    },

    // Thème Taxi Blue (Bleu/Blanc)
    KoogweTheme.taxiBlue: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Taxi Blue',
        description: 'Style application de taxi premium',
        icon: Icons.local_taxi,
        primary: const Color(0xFF2196F3),
        primaryDark: const Color(0xFF1976D2),
        secondary: const Color(0xFF03A9F4),
        accent: const Color(0xFFFFC107),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFF5F5F5),
        surfaceVariant: const Color(0xFFEEEEEE),
        textPrimary: const Color(0xFF212121),
        textSecondary: const Color(0xFF757575),
        textTertiary: const Color(0xFFBDBDBD),
        border: const Color(0xFFE0E0E0),
        error: const Color(0xFFF44336),
        success: const Color(0xFF4CAF50),
        warning: const Color(0xFFFF9800),
        gradientBackground: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF2196F3), Color(0xFF03A9F4)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Taxi Blue',
        description: 'Taxi Blue (Sombre)',
        icon: Icons.local_taxi,
        primary: const Color(0xFF42A5F5),
        primaryDark: const Color(0xFF2196F3),
        secondary: const Color(0xFF29B6F6),
        accent: const Color(0xFFFFD54F),
        background: const Color(0xFF121212),
        surface: const Color(0xFF1E1E1E),
        surfaceVariant: const Color(0xFF2C2C2C),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFB0B0B0),
        textTertiary: const Color(0xFF707070),
        border: const Color(0xFF3A3A3A),
        error: const Color(0xFFEF5350),
        success: const Color(0xFF66BB6A),
        warning: const Color(0xFFFFB74D),
      ),
    },

    // Thème Smart Home (Gradient Bleu/Violet/Rose)
    KoogweTheme.smartHome: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Smart Home',
        description: 'Gradient moderne bleu/violet/rose',
        icon: Icons.home,
        primary: const Color(0xFF6366F1),
        primaryDark: const Color(0xFF4F46E5),
        secondary: const Color(0xFF8B5CF6),
        accent: const Color(0xFFEC4899),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFF8FAFC),
        surfaceVariant: const Color(0xFFF1F5F9),
        textPrimary: const Color(0xFF0F172A),
        textSecondary: const Color(0xFF64748B),
        textTertiary: const Color(0xFFCBD5E1),
        border: const Color(0xFFE2E8F0),
        error: const Color(0xFFEF4444),
        success: const Color(0xFF10B981),
        warning: const Color(0xFFF59E0B),
        gradientBackground: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF6366F1), Color(0xFF8B5CF6), Color(0xFFEC4899)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Smart Home',
        description: 'Smart Home (Sombre)',
        icon: Icons.home,
        primary: const Color(0xFF818CF8),
        primaryDark: const Color(0xFF6366F1),
        secondary: const Color(0xFFA78BFA),
        accent: const Color(0xFFF472B6),
        background: const Color(0xFF0F172A),
        surface: const Color(0xFF1E293B),
        surfaceVariant: const Color(0xFF334155),
        textPrimary: const Color(0xFFF8FAFC),
        textSecondary: const Color(0xFFCBD5E1),
        textTertiary: const Color(0xFF64748B),
        border: const Color(0xFF475569),
        error: const Color(0xFFF87171),
        success: const Color(0xFF34D399),
        warning: const Color(0xFFFBBF24),
      ),
    },

    // Thème Bus Coral (Corail/Gris foncé)
    KoogweTheme.busCoral: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Bus Coral',
        description: 'Style réservation de bus moderne',
        icon: Icons.directions_bus,
        primary: const Color(0xFFFF6B6B),
        primaryDark: const Color(0xFFEE5A52),
        secondary: const Color(0xFF4ECDC4),
        accent: const Color(0xFFFFE66D),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFFAFAFA),
        surfaceVariant: const Color(0xFFF5F5F5),
        textPrimary: const Color(0xFF2C2C2C),
        textSecondary: const Color(0xFF757575),
        textTertiary: const Color(0xFFBDBDBD),
        border: const Color(0xFFE0E0E0),
        error: const Color(0xFFFF5252),
        success: const Color(0xFF4CAF50),
        warning: const Color(0xFFFFB74D),
        gradientBackground: const LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: [Color(0xFFFF6B6B), Color(0xFFFF8E8E)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Bus Coral',
        description: 'Bus Coral (Sombre)',
        icon: Icons.directions_bus,
        primary: const Color(0xFFFF8787),
        primaryDark: const Color(0xFFFF6B6B),
        secondary: const Color(0xFF66D9D9),
        accent: const Color(0xFFFFF176),
        background: const Color(0xFF1A1A1A),
        surface: const Color(0xFF252525),
        surfaceVariant: const Color(0xFF323232),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFB0B0B0),
        textTertiary: const Color(0xFF707070),
        border: const Color(0xFF404040),
        error: const Color(0xFFFF6B6B),
        success: const Color(0xFF66BB6A),
        warning: const Color(0xFFFFB74D),
      ),
    },

    // Thème Fitness Gradient (Orange/Violet)
    KoogweTheme.fitnessGradient: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Fitness Gradient',
        description: 'Gradient énergique orange/violet',
        icon: Icons.fitness_center,
        primary: const Color(0xFFFF6B35),
        primaryDark: const Color(0xFFE63946),
        secondary: const Color(0xFF9B59B6),
        accent: const Color(0xFFE91E63),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFF8F9FA),
        surfaceVariant: const Color(0xFFE9ECEF),
        textPrimary: const Color(0xFF212529),
        textSecondary: const Color(0xFF6C757D),
        textTertiary: const Color(0xFFADB5BD),
        border: const Color(0xFFDEE2E6),
        error: const Color(0xFFDC3545),
        success: const Color(0xFF28A745),
        warning: const Color(0xFFFFC107),
        gradientBackground: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFFFF6B35), Color(0xFF9B59B6), Color(0xFFE91E63)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Fitness Gradient',
        description: 'Fitness Gradient (Sombre)',
        icon: Icons.fitness_center,
        primary: const Color(0xFFFF8C5A),
        primaryDark: const Color(0xFFFF6B35),
        secondary: const Color(0xFFB182D9),
        accent: const Color(0xFFF06292),
        background: const Color(0xFF121212),
        surface: const Color(0xFF1E1E1E),
        surfaceVariant: const Color(0xFF2C2C2C),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFB0B0B0),
        textTertiary: const Color(0xFF707070),
        border: const Color(0xFF3A3A3A),
        error: const Color(0xFFEF5350),
        success: const Color(0xFF66BB6A),
        warning: const Color(0xFFFFB74D),
      ),
    },

    // Thème Auth Brown (Marron/Gris foncé)
    KoogweTheme.authBrown: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Auth Brown',
        description: 'Style authentification élégant',
        icon: Icons.lock,
        primary: const Color(0xFF8B6914),
        primaryDark: const Color(0xFF6B4E0F),
        secondary: const Color(0xFFD4AF37),
        accent: const Color(0xFFFFD700),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFFAF9F6),
        surfaceVariant: const Color(0xFFF5F3ED),
        textPrimary: const Color(0xFF2C2C2C),
        textSecondary: const Color(0xFF757575),
        textTertiary: const Color(0xFFBDBDBD),
        border: const Color(0xFFE0E0E0),
        error: const Color(0xFFC62828),
        success: const Color(0xFF2E7D32),
        warning: const Color(0xFFF57C00),
        gradientBackground: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF8B6914), Color(0xFFD4AF37)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Auth Brown',
        description: 'Auth Brown (Sombre)',
        icon: Icons.lock,
        primary: const Color(0xFFD4AF37),
        primaryDark: const Color(0xFF8B6914),
        secondary: const Color(0xFFFFD700),
        accent: const Color(0xFFFFE082),
        background: const Color(0xFF1A1A1A),
        surface: const Color(0xFF252525),
        surfaceVariant: const Color(0xFF323232),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFB0B0B0),
        textTertiary: const Color(0xFF707070),
        border: const Color(0xFF404040),
        error: const Color(0xFFE53935),
        success: const Color(0xFF4CAF50),
        warning: const Color(0xFFFFB300),
      ),
    },

    // Thème Ocean Blue (Bleu océan)
    KoogweTheme.oceanBlue: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Ocean Blue',
        description: 'Bleu océan apaisant',
        icon: Icons.water_drop,
        primary: const Color(0xFF0288D1),
        primaryDark: const Color(0xFF01579B),
        secondary: const Color(0xFF00BCD4),
        accent: const Color(0xFF26C6DA),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFE3F2FD),
        surfaceVariant: const Color(0xFFBBDEFB),
        textPrimary: const Color(0xFF01579B),
        textSecondary: const Color(0xFF0288D1),
        textTertiary: const Color(0xFF81D4FA),
        border: const Color(0xFF90CAF9),
        error: const Color(0xFFD32F2F),
        success: const Color(0xFF388E3C),
        warning: const Color(0xFFF57C00),
        gradientBackground: const LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: [Color(0xFF0288D1), Color(0xFF00BCD4)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Ocean Blue',
        description: 'Ocean Blue (Sombre)',
        icon: Icons.water_drop,
        primary: const Color(0xFF29B6F6),
        primaryDark: const Color(0xFF0288D1),
        secondary: const Color(0xFF4DD0E1),
        accent: const Color(0xFF4FC3F7),
        background: const Color(0xFF0D47A1),
        surface: const Color(0xFF1565C0),
        surfaceVariant: const Color(0xFF1976D2),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFBBDEFB),
        textTertiary: const Color(0xFF90CAF9),
        border: const Color(0xFF64B5F6),
        error: const Color(0xFFEF5350),
        success: const Color(0xFF66BB6A),
        warning: const Color(0xFFFFB74D),
      ),
    },

    // Thème Sunset Purple (Violet coucher de soleil)
    KoogweTheme.sunsetPurple: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Sunset Purple',
        description: 'Violet et rose coucher de soleil',
        icon: Icons.wb_twilight,
        primary: const Color(0xFF7B2CBF),
        primaryDark: const Color(0xFF5A189A),
        secondary: const Color(0xFF9D4EDD),
        accent: const Color(0xFFFF006E),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFFAF5FF),
        surfaceVariant: const Color(0xFFF3E8FF),
        textPrimary: const Color(0xFF4A148C),
        textSecondary: const Color(0xFF7B2CBF),
        textTertiary: const Color(0xFFC77DFF),
        border: const Color(0xFFE0AAFF),
        error: const Color(0xFFB71C1C),
        success: const Color(0xFF1B5E20),
        warning: const Color(0xFFE65100),
        gradientBackground: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF7B2CBF), Color(0xFF9D4EDD), Color(0xFFFF006E)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Sunset Purple',
        description: 'Sunset Purple (Sombre)',
        icon: Icons.wb_twilight,
        primary: const Color(0xFF9D4EDD),
        primaryDark: const Color(0xFF7B2CBF),
        secondary: const Color(0xFFC77DFF),
        accent: const Color(0xFFFF4FA7),
        background: const Color(0xFF240046),
        surface: const Color(0xFF3C096C),
        surfaceVariant: const Color(0xFF5A189A),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFE0AAFF),
        textTertiary: const Color(0xFFC77DFF),
        border: const Color(0xFF9D4EDD),
        error: const Color(0xFFEF5350),
        success: const Color(0xFF66BB6A),
        warning: const Color(0xFFFFB74D),
      ),
    },

    // Thème Forest Green (Vert forêt)
    KoogweTheme.forestGreen: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Forest Green',
        description: 'Vert nature apaisant',
        icon: Icons.forest,
        primary: const Color(0xFF2E7D32),
        primaryDark: const Color(0xFF1B5E20),
        secondary: const Color(0xFF66BB6A),
        accent: const Color(0xFF81C784),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFF1F8E9),
        surfaceVariant: const Color(0xFFDCEDC8),
        textPrimary: const Color(0xFF1B5E20),
        textSecondary: const Color(0xFF2E7D32),
        textTertiary: const Color(0xFF81C784),
        border: const Color(0xFFAED581),
        error: const Color(0xFFC62828),
        success: const Color(0xFF2E7D32),
        warning: const Color(0xFFF57C00),
        gradientBackground: const LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: [Color(0xFF2E7D32), Color(0xFF66BB6A)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Forest Green',
        description: 'Forest Green (Sombre)',
        icon: Icons.forest,
        primary: const Color(0xFF66BB6A),
        primaryDark: const Color(0xFF2E7D32),
        secondary: const Color(0xFF81C784),
        accent: const Color(0xFFA5D6A7),
        background: const Color(0xFF1B5E20),
        surface: const Color(0xFF2E7D32),
        surfaceVariant: const Color(0xFF388E3C),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFC8E6C9),
        textTertiary: const Color(0xFFA5D6A7),
        border: const Color(0xFF81C784),
        error: const Color(0xFFEF5350),
        success: const Color(0xFF66BB6A),
        warning: const Color(0xFFFFB74D),
      ),
    },

    // Thème Midnight Dark (Noir minuit)
    KoogweTheme.midnightDark: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Midnight Dark',
        description: 'Noir minuit élégant',
        icon: Icons.dark_mode,
        primary: const Color(0xFF1A1A1A),
        primaryDark: const Color(0xFF000000),
        secondary: const Color(0xFF424242),
        accent: const Color(0xFFFFD700),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFFAFAFA),
        surfaceVariant: const Color(0xFFF5F5F5),
        textPrimary: const Color(0xFF1A1A1A),
        textSecondary: const Color(0xFF757575),
        textTertiary: const Color(0xFFBDBDBD),
        border: const Color(0xFFE0E0E0),
        error: const Color(0xFFD32F2F),
        success: const Color(0xFF388E3C),
        warning: const Color(0xFFF57C00),
        gradientBackground: const LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: [Color(0xFF1A1A1A), Color(0xFF424242)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Midnight Dark',
        description: 'Midnight Dark (Sombre)',
        icon: Icons.dark_mode,
        primary: const Color(0xFFFFFFFF),
        primaryDark: const Color(0xFFE0E0E0),
        secondary: const Color(0xFF757575),
        accent: const Color(0xFFFFD700),
        background: const Color(0xFF000000),
        surface: const Color(0xFF1A1A1A),
        surfaceVariant: const Color(0xFF2C2C2C),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFFB0B0B0),
        textTertiary: const Color(0xFF707070),
        border: const Color(0xFF404040),
        error: const Color(0xFFEF5350),
        success: const Color(0xFF66BB6A),
        warning: const Color(0xFFFFB74D),
      ),
    },

    // Thème Cyber Punk (Néon cyberpunk)
    KoogweTheme.cyberPunk: {
      KoogweThemeMode.light: KoogweThemeData(
        name: 'Cyber Punk',
        description: 'Néon cyberpunk futuriste',
        icon: Icons.bolt,
        primary: const Color(0xFF00FF88),
        primaryDark: const Color(0xFF00CC6A),
        secondary: const Color(0xFFFF00FF),
        accent: const Color(0xFF00FFFF),
        background: const Color(0xFFFFFFFF),
        surface: const Color(0xFFF0F0F0),
        surfaceVariant: const Color(0xFFE0E0E0),
        textPrimary: const Color(0xFF000000),
        textSecondary: const Color(0xFF333333),
        textTertiary: const Color(0xFF666666),
        border: const Color(0xFFCCCCCC),
        error: const Color(0xFFFF0055),
        success: const Color(0xFF00FF88),
        warning: const Color(0xFFFFAA00),
        gradientBackground: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF00FF88), Color(0xFFFF00FF), Color(0xFF00FFFF)],
        ),
      ),
      KoogweThemeMode.dark: KoogweThemeData(
        name: 'Cyber Punk',
        description: 'Cyber Punk (Sombre)',
        icon: Icons.bolt,
        primary: const Color(0xFF00FF88),
        primaryDark: const Color(0xFF00CC6A),
        secondary: const Color(0xFFFF00FF),
        accent: const Color(0xFF00FFFF),
        background: const Color(0xFF000000),
        surface: const Color(0xFF0A0A0A),
        surfaceVariant: const Color(0xFF1A1A1A),
        textPrimary: const Color(0xFFFFFFFF),
        textSecondary: const Color(0xFF00FF88),
        textTertiary: const Color(0xFF00CC6A),
        border: const Color(0xFF333333),
        error: const Color(0xFFFF0055),
        success: const Color(0xFF00FF88),
        warning: const Color(0xFFFFAA00),
        gradientBackground: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF00FF88), Color(0xFFFF00FF), Color(0xFF00FFFF)],
        ),
      ),
    },
  };

  static KoogweThemeData getTheme(KoogweTheme theme, KoogweThemeMode mode) {
    return allThemes[theme]?[mode] ?? allThemes[KoogweTheme.defaultOrange]![mode]!;
  }

  static List<KoogweTheme> get availableThemes => KoogweTheme.values;
}

